service: locatotron-frontend

frameworkVersion: ">=1.10.0"

provider:
  name: aws
  runtime: nodejs6.10
  profile: locatotron
  stage: dev

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${file(../config.${self:provider.stage}.json):frontend.bucket}
    distributionFolder: dist
    indexDocument: index.html
    errorDocument: error.html
